import { library } from '@fortawesome/fontawesome-svg-core';
import {
	faFacebook as fabFacebook,
	faGoogle as fabGoogle,
} from '@fortawesome/free-brands-svg-icons';
import {
	faAngleDoubleLeft as fadAngleDoubleLeft,
	faAngleDoubleRight as fadAngleDoubleRight,
	faAngleLeft as fadAngleLeft,
	faAngleRight as fadAngleRight,
	faArrowCircleRight as fadArrowCircleRight,
	faAt as fadAt,
	faBars as fadBars,
	faCaretLeft as fadCaretLeft,
	faCaretRight as fadCaretRight,
	faCheck as fadCheck,
	faEdit as fadEdit,
	faEnvelope as fadEnvelope,
	faEnvelopeOpen as fadEnvelopeOpen,
	faExclamationTriangle as fadExclamationTriangle,
	faExternalLink as fadExternalLink,
	faFlag as fadFlag,
	faInfoCircle as fadInfoCircle,
	faLemon as fadLemon,
	faLock as fadLock,
	faMagic as fadMagic,
	faMoneyBill as fadMoney,
	faPrint as fadPrint,
	faQuestionCircle as fadQuestionCircle,
	faReply as fadReply,
	faSave as fadSave,
	faSignOut as fadSignOut,
	faSortSizeDown as fadSortSizeDown,
	faSortSizeUp as fadSortSizeUp,
	faSpinner as fadSpinner,
	faSync as fadSync,
	faThumbsDown as fadThumbsDown,
	faThumbsUp as fadThumbsUp,
	faTimes as fadTimes,
	faTrash as fadTrash,
	faUserSecret as fadUserSecret,
} from '@fortawesome/pro-duotone-svg-icons';

library.add(
	fabFacebook,
	fabGoogle,
	fadAngleDoubleLeft,
	fadAngleDoubleRight,
	fadAngleLeft,
	fadAngleRight,
	fadArrowCircleRight,
	fadAt,
	fadBars,
	fadCaretLeft,
	fadCaretRight,
	fadCheck,
	fadEdit,
	fadEnvelope,
	fadEnvelopeOpen,
	fadExclamationTriangle,
	fadExternalLink,
	fadFlag,
	fadInfoCircle,
	fadLemon,
	fadLock,
	fadMagic,
	fadMoney,
	fadPrint,
	fadQuestionCircle,
	fadReply,
	fadSave,
	fadSignOut,
	fadSortSizeDown,
	fadSortSizeUp,
	fadSpinner,
	fadSync,
	fadThumbsDown,
	fadThumbsUp,
	fadTimes,
	fadTrash,
	fadUserSecret,
);
