// Generated by typings
// Source: https://raw.githubusercontent.com/twastvedt/typed-meteor-validated-method/f5816fc26ca5b8c9eee211b193e87833f384da21/index.d.ts
declare class ValidatedMethod<T> extends MeteorValidatedMethod.ValidatedMethod<
	T
> {}

declare namespace MeteorValidatedMethod {
	export class ValidatedMethod<T> {
		constructor (options: ValidatedMethodOptions<T>);
		call (options?: T, cb?: (err, res) => void): void;
	}

	interface ValidatedMethodOptions<T> {
		name: string;
		mixins?: Function[];
		validate: any;
		run(opts: T);
	}
}
